### ISSUE TITLE
Add heading "Current JPO opportunities at WFP"

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-jpo-country#1]
After the introductory paragraph and before the vacancy, the title "Current JPO opportunities at WFP".
![jpo country mockup](https://cloud.githubusercontent.com/assets/19909772/17974661/37c2eaae-6ae7-11e6-91a5-88ad0bf3d748.PNG)

A note for development: 
when there are no vacancies for the specific country we could implement one of the two followings:
1. hide the heading
2. show a different text. Something like "There are no job opportunities available at the moment, please check again soon"

**Comment by jrah** [comment]
This is something that will be implemented by the Drupal developers. 

(2) seems like the best option to maximise user experience.

/cc @matthewmorek

**Comment by matthewmorek** [comment]
I agree with James, [2] looks to be the best option, instead of serving just the introduction text. As above, this is something that should be added as an issue to `wfp/wfp-org-d8` once the template is implemented, so this could be followed up.
